=== AlimG11/Database/marketbase.dtd
<!ELEMENT marketbase (description, database_system, tables, dependencies, roles, ui_api, technology)>
<!ELEMENT description (project, domain, target)>
<!ELEMENT project (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT database_system (#PCDATA)>

<!ELEMENT tables (users, product_categories, products, purchase_history, supply_history)>
<!ELEMENT users (user_id, username, password, user_role, created_at)>
<!ELEMENT product_categories (category_id, category_name, seller_id)>
<!ELEMENT products (product_id, seller_id, category_id, product_name, description, price, total_quantity, date_of_update)>
<!ELEMENT purchase_history (purchase_id, client_id, product_id, quantity, price, total_price, purchase_date)>
<!ELEMENT supply_history (supply_id, seller_id, product_id, quantity, supply_date)>

<!ELEMENT user_id (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT user_role (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>

<!ELEMENT category_id (#PCDATA)>
<!ELEMENT category_name (#PCDATA)>
<!ELEMENT seller_id (#PCDATA)>

<!ELEMENT product_id (#PCDATA)>
<!ELEMENT product_name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT total_quantity (#PCDATA)>
<!ELEMENT date_of_update (#PCDATA)>

<!ELEMENT purchase_id (#PCDATA)>
<!ELEMENT client_id (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT total_price (#PCDATA)>
<!ELEMENT purchase_date (#PCDATA)>

<!ELEMENT supply_id (#PCDATA)>
<!ELEMENT supply_date (#PCDATA)>

<!ELEMENT dependencies (relation*)>
<!ELEMENT relation EMPTY>
<!ATTLIST relation from CDATA #REQUIRED>
<!ATTLIST relation to CDATA #REQUIRED>
<!ATTLIST relation type CDATA #REQUIRED>

<!ELEMENT roles (role*)>
<!ELEMENT role (responsibility)>
<!ATTLIST role name CDATA #REQUIRED>
<!ELEMENT responsibility (#PCDATA)>

<!ELEMENT ui_api (interface)>
<!ELEMENT interface (#PCDATA)>

<!ELEMENT technology (programming_language, database)>
<!ELEMENT programming_language (#PCDATA)>
<!ELEMENT database (#PCDATA)>

=== AlimG11/Database/marketbase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marketbase SYSTEM "marketbase.dtd">
<marketbase>
    <description>
        <project>MarketBase</project>
        <domain>Торговля и логистика</domain>
        <target>Предприятия розничной и оптовой торговли</target>
    </description>
    <database_system>PostgreSQL</database_system>
    <tables>
        <users>
            <user_id type="SERIAL" primary_key="true" not_null="true" />
            <username type="VARCHAR(32)" not_null="true" unique="true" />
            <password type="VARCHAR(32)" not_null="true" />
            <user_role type="VARCHAR(6)" not_null="true" />
            <created_at type="DATE" not_null="true" />
        </users>
        <product_categories>
            <category_id type="SERIAL" primary_key="true" not_null="true" />
            <category_name type="VARCHAR(64)" not_null="true" unique="true" />
            <seller_id type="INTEGER" not_null="true" references="users(user_id)" />
        </product_categories>
        <products>
            <product_id type="SERIAL" primary_key="true" not_null="true" />
            <seller_id type="INTEGER" not_null="true" references="users(user_id)" />
            <category_id type="INTEGER" not_null="true" references="product_categories(category_id)" />
            <product_name type="VARCHAR(64)" not_null="true" />
            <description type="VARCHAR(256)" not_null="true" />
            <price type="NUMERIC(10,2)" not_null="true" />
            <total_quantity type="INTEGER" not_null="true" default="0" />
            <date_of_update type="DATE" not_null="true" />
        </products>
        <purchase_history>
            <purchase_id type="SERIAL" primary_key="true" not_null="true" />
            <client_id type="INTEGER" not_null="true" references="users(user_id)" />
            <product_id type="INTEGER" not_null="true" references="products(product_id)" />
            <quantity type="INTEGER" not_null="true" />
            <price type="NUMERIC" not_null="true" />
            <total_price type="NUMERIC(10,2)" not_null="true" />
            <purchase_date type="DATE" not_null="true" />
        </purchase_history>
        <supply_history>
            <supply_id type="SERIAL" primary_key="true" not_null="true" />
            <seller_id type="INTEGER" not_null="true" references="users(user_id)" />
            <product_id type="INTEGER" not_null="true" references="products(product_id)" />
            <quantity type="INTEGER" not_null="true" />
            <supply_date type="DATE" not_null="true" />
        </supply_history>
    </tables>
    <dependencies>
        <relation from="products" to="users" type="many_to_one" />
        <relation from="products" to="product_categories" type="many_to_one" />
        <relation from="purchase_history" to="users" type="many_to_one" />
        <relation from="purchase_history" to="products" type="many_to_one" />
        <relation from="supply_history" to="users" type="many_to_one" />
        <relation from="supply_history" to="products" type="many_to_one" />
        <relation from="product_categories" to="users" type="many_to_one" />
    </dependencies>
    <roles>
        <role name="seller">
            <responsibility>Выставляет новые товары на продажу и добавляет новые категории</responsibility>
        </role>
        <role name="client">
            <responsibility>Может покупать товары</responsibility>
        </role>
    </roles>
    <ui_api>
        <interface>Консольный интерфейс</interface>
    </ui_api>
    <technology>
        <programming_language>Python</programming_language>
        <database>PostgreSQL</database>
    </technology>
</marketbase>
